-- Project: Flights Data Engineering
-- File: 05_create_grants.sql
-- Purpose: Grant permissions to project roles

USE ROLE SECURITYADMIN;

-- ----------------
-- WAREHOUSE GRANTS
-- ----------------

--Fivetran uses the ingestion warehouse
GRANT USAGE ON WAREHOUSE LOAD_WH
TO ROLE FIVETRAN_ROLE;

-- dbt uses the transformation warehouse
GRANT USAGE ON WAREHOUSE TRANSFORM_WH
TO ROLE DBT_ROLE;

-- Tableau uses the BI warehouse
GRANT USAGE ON WAREHOUSE BI_WH
TO ROLE BI_ROLE;

-- Project admins can use all warehouses
GRANT USAGE ON WAREHOUSE LOAD_WH
TO ROLE DATA_ENGINEER_ROLE;

GRANT USAGE ON WAREHOUSE TRANSFORM_WH
TO ROLE DATA_ENGINEER_ROLE;

GRANT USAGE ON WAREHOUSE BI_WH
TO ROLE DATA_ENGINEER_ROLE;


-- ----------------
-- Database Grants
-- ----------------

-- Fivetran
GRANT USAGE ON DATABASE FLIGHTS_RAW
TO ROLE FIVETRAN_ROLE;

-- dbt

GRANT USAGE ON DATABASE FLIGHTS_RAW
TO ROLE DBT_ROLE;

GRANT USAGE ON DATABASE FLIGHTS_ANALYTICS
TO ROLE DBT_ROLE;

-- BI

GRANT USAGE ON DATABASE FLIGHTS_ANALYTICS
TO ROLE BI_ROLE;

-- DEVELOPER
GRANT USAGE ON DATABASE FLIGHTS_RAW
TO ROLE DATA_ENGINEER_ROLE;

GRANT USAGE ON DATABASE FLIGHTS_ANALYTICS
TO ROLE ON DATA_ENGINEER_ROLE;

-- -------------
-- Schema Grants
-- -------------

-- Fivetran
GRANT USAGE ON SCHEMA FLIGHTS_RAW.RAW
TO ROLE FIVETRAN_FILE;

-- dbt

GRANT USAGE ON SCHEMA FLIGHTS_RAW.RAW
TO ROLE DBT_ROLE;

GRANT USAGE ON SCHEMA FLIGHTS_ANALYTICS.STAGING
TO ROLE DBT_ROLE;

GRANT USAGE ON SCHEMA FLIGHTS_ANALYTICS.INTERMEDIATE
TO ROLE DBT_ROLE;

GRANT USAGE ON SCHEMA FLIGHTS_ANALYTICS.MARTS
TO ROLE DBT_ROLE;

GRANT USAGE ON SCHEMA FLIGHTS_ANALYTICS.SEMANTIC
TO ROLE DBT_ROLE;

-- BI

GRANT USAGE ON SCHEMA FLIGHTS_ANALYTICS.SEMANTIC
TO ROLE BI_ROLE;

-- Developer

GRANT USAGE ON ALL SCHEMAS IN DATABASE FLIGHTS_ANALYTICS
TO ROLE DATA_ENGINEER_ROLE;

GRANT USAGE ON SCHEMA FLIGHTS_RAW.RAW
TO ROLE DATA_ENGINEER_ROLE;